# Task-1 
# Pipeline to Run the Sample Python Application in GitHub Account
# Before running the pipeline make sure that the App file is present in the GitHub Account
# GitHub Repository Link: https://github.com/Kureti-Venkat-Nishit-Pvt/DevOps_Assignment/blob/main/Hello_Hexaware.py 

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
      versionSpec: '3.x'

- script: |
    python -m pip install --upgrade pip
    python Hello_Hexaware.py
  displayName: 'Run Hello_Hexaware Sample Application in GitHub using Azure DevOps'
